SELECT
	S_JISHUI_MONITOR_HIS.S_NO,
	S_JISHUI_MONITOR_HIS.T_SYSTIME,
	S_JISHUI_MONITOR_HIS.N_VALUE,
	S_JISHUI_MONITOR_HIS.S_HASMONITOR,
	S_JISHUI_MONITOR_HIS.S_STATENAME,
	T_JISHUI.S_ADDR,
	T_JISHUI.S_BUILDDATE,
	T_JISHUI.S_PROUNIT,
	T_JISHUI.S_MANAGE_UNIT,
	T_JISHUI.S_MAINTAIN_UNIT,
	T_JISHUI.S_STATIONID,
	T_JISHUI.S_STATIONNAME
FROM
	S_JISHUI_MONITOR_HIS
	LEFT JOIN T_JISHUI ON S_JISHUI_MONITOR_HIS.S_NO = T_JISHUI.S_NO
WHERE
	S_JISHUI_MONITOR_HIS.T_SYSTIME >= TO_DATE( '{start_time}', 'YYYY-MM-DD HH24:MI:SS' )
	AND S_JISHUI_MONITOR_HIS.T_SYSTIME < TO_DATE( '{end_time}', 'YYYY-MM-DD HH24:MI:SS' )
	AND T_JISHUI.S_MONTYPE = 'PS1301'