SELECT
	T_JISHUI_HISTORY.S_NO,
	T_JISHUI_HISTORY.T_SYSTIME,
	T_JISHUI_HISTORY.N_VALUE,
	T_JISHUI_MONITOR.S_HASMONITOR,
	T_JISHUI_MONITOR.S_ISUSE AS S_STATENAME,
	T_JISHUI_MONITOR.S_ADDR,
	T_JISHUI_MONITOR.S_BUILDDATE,
	T_JISHUI_MONITOR.S_UP_PROUNIT AS S_PROUNIT,
	T_JISHUI_MONITOR.S_MANAGE_UNIT,
	T_JISHUI_MONITOR.S_MAINTAIN_UNIT,
	T_JISHUI_RAINSTATIONS.S_STATION_NO AS S_STATIONID,
	T_JISHUI_RAINSTATIONS.S_STATION_NAME AS S_STATIONNAME
FROM
	T_JISHUI_HISTORY
	LEFT JOIN sde.T_JISHUI_MONITOR ON T_JISHUI_HISTORY.S_NO = T_JISHUI_MONITOR.S_NO
	LEFT JOIN T_JISHUI_RAINSTATIONS ON T_JISHUI_HISTORY.S_NO = T_JISHUI_RAINSTATIONS.S_NO
WHERE
	T_JISHUI_HISTORY.T_SYSTIME >= '{start_time}'
	AND T_JISHUI_HISTORY.T_SYSTIME < '{end_time}'
	AND T_JISHUI_MONITOR.S_MONTYPE = 'PS1301'

