SELECT
	S_STID,
	S_BJBH,
	S_BJTYPE,
	S_PUMPTYPE,
	S_KTBZT,
	T_KBTIME,
	T_TBTIME,
	N_KBSW,
	N_TBSW
FROM
	T_KTBMX_HIS
WHERE
	T_KBTIME >= TO_DATE( '{start_time}', 'YYYY-MM-DD HH24:MI:SS' )
	AND T_KBTIME < TO_DATE( '{end_time}', 'YYYY-MM-DD HH24:MI:SS' )