SELECT
	S_YULIANG_MIN_HIS.S_STATIONID,
	S_YULIANG_MIN_HIS.D_TIME,
	S_YULIANG_MIN_HIS.N_RAINVALUE,
	S_YULIANG_MIN_HIS.S_STATIONNAME,
	T_DRAIN_STATION.S_DIST,
	T_DRAIN_STATION.S_XIANGZHEN
FROM
	S_YULIANG_MIN_HIS
	LEFT JOIN T_DRAIN_STATION ON S_YULIANG_MIN_HIS.S_STATIONID = T_DRAIN_STATION.S_STATIONID
WHERE
	D_TIME >= TO_DATE( '{start_time}', 'YYYY-MM-DD HH24:MI:SS' )
	AND D_TIME < TO_DATE( '{end_time}', 'YYYY-MM-DD HH24:MI:SS' )