SELECT
	JI.S_NO,
	JI.S_ADDR,
	JI.S_PSXT,
	JI.S_DIRECTTO,
	JI.S_JSGGJ,
	JI.S_JSGYX,
	JI.S_CSGGJ,
	JI.S_CSGYX,
	JI.S_SBTS,
	JI.S_SBLL,
	JI.S_XTBM,
	JI.S_STATIONID,
	PM.S_DRAI_PUMP_NAME,
	PM.S_DRAI_PUMP_ADD,
	PM.N_DRAI_PUMP_FLOW_FACT_Y,
	PM.N_DRAI_PUMP_FLOW_FACT_W,
	PM.N_DRAI_PUMP_POW_SUM_Y,
	PM.N_DRAI_PUMP_POW_SUM_W,
	PM.N_DISTRICT,
	PM.N_DRAI_PUMP_TYPE,
	PM.N_DRAI_PUMP_TYPE_FEAT,
	PM.S_PUMPS_TYPE,
	PM.N_PUMPS_NUM,
	PM.N_PUMPS_FLOW,
	DA.S_STID,
	DA.S_ZONE_ID
FROM
	T_JISHUI JI
	LEFT JOIN V_OVERPUMP PM ON JI.S_XTBM = PM.S_XTBM
	LEFT JOIN T_DRAINPUMP_ADD DA ON JI.S_XTBM = DA.S_XTBM