SELECT
	TB_YULIANG_5MIN.ST_STATIONID as S_STATIONID,
	TB_YULIANG_5MIN.DT_TIME as D_TIME,
	TB_YULIANG_5MIN.NM_RAINVALUE as N_RAINVALUE,
	TB_YULIANG_5MIN.ST_STATIONNAME as S_STATIONNAME,
	T_DRAIN_STATION.S_DIST as S_DIST,
	T_DRAIN_STATION.S_DIST as S_XIANGZHEN
FROM
	SWCORE.TB_YULIANG_5MIN
	LEFT JOIN YXJG_WAVENET.T_DRAIN_STATION ON TB_YULIANG_5MIN.ST_STATIONID = T_DRAIN_STATION.S_STATIONID
WHERE
	DT_TIME >= TO_DATE( '{start_time}', 'YYYY-MM-DD HH24:MI:SS' )
	AND DT_TIME < TO_DATE( '{end_time}', 'YYYY-MM-DD HH24:MI:SS' )